import nodemailer from 'nodemailer';
import 'dotenv/config';

const transporter = nodemailer.createTransporter({
  service: 'Gmail',
  host: 'smtp.gmail.com',
  port: 465,
  secure: true,
  auth: {
    user: process.env.EMAIL_USERNAME,
    pass: process.env.GMAIL_APP_PASSWORD,
  },
});

(async () => {
  try {
    await transporter.sendMail({
      from: '"GitHub Actions Automation" <' + process.env.EMAIL_USERNAME + '>',
      to: 'sean.esparagoza@gmail.com', // UPDATE THIS EMAIL ADDRESS
      subject: 'Automated Report from GitHub Actions',
      html: `
        <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
          <h2 style="color: #0366d6;">Daily Report - GitHub Actions</h2>
          <p>This is an automated email from your GitHub Actions workflow.</p>
          
          <table style="border-collapse: collapse; width: 100%; margin: 20px 0;">
            <tr style="background-color: #f6f8fa;">
              <td style="padding: 10px; border: 1px solid #d0d7de; font-weight: bold;">Repository:</td>
              <td style="padding: 10px; border: 1px solid #d0d7de;">${process.env.GITHUB_REPOSITORY}</td>
            </tr>
            <tr>
              <td style="padding: 10px; border: 1px solid #d0d7de; font-weight: bold;">Workflow:</td>
              <td style="padding: 10px; border: 1px solid #d0d7de;">${process.env.GITHUB_WORKFLOW}</td>
            </tr>
            <tr style="background-color: #f6f8fa;">
              <td style="padding: 10px; border: 1px solid #d0d7de; font-weight: bold;">Run ID:</td>
              <td style="padding: 10px; border: 1px solid #d0d7de;">${process.env.GITHUB_RUN_ID}</td>
            </tr>
            <tr>
              <td style="padding: 10px; border: 1px solid #d0d7de; font-weight: bold;">Actor:</td>
              <td style="padding: 10px; border: 1px solid #d0d7de;">${process.env.GITHUB_ACTOR}</td>
            </tr>
            <tr style="background-color: #f6f8fa;">
              <td style="padding: 10px; border: 1px solid #d0d7de; font-weight: bold;">Timestamp:</td>
              <td style="padding: 10px; border: 1px solid #d0d7de;">${new Date().toISOString()}</td>
            </tr>
          </table>
          
          <p style="margin-top: 30px; color: #586069; font-size: 12px;">
            This email was automatically generated by GitHub Actions. 
            If you no longer wish to receive these emails, please contact your repository administrator.
          </p>
        </div>
      `,
    });
    console.log('Email sent successfully!');
  } catch (error) {
    console.error('Error sending email:', error);
    process.exit(1);
  }
})();
