name: Copilot Solution Monitor

on:
  pull_request:
    types: [opened, synchronize]
    # Monitor for PRs from Copilot
  pull_request_review:
    types: [submitted]
  issues:
    types: [closed]

permissions:
  contents: read
  issues: read
  pull-requests: read

jobs:
  monitor-copilot-solutions:
    runs-on: ubuntu-latest
    if: github.actor == 'copilot[bot]' || contains(github.event.pull_request.title, 'Programming Problem') || contains(github.event.issue.title, 'Programming Problem')
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Get PR Details
        id: pr-details
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { data: pr } = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number
            });

            const { data: files } = await github.rest.pulls.listFiles({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number
            });

            return {
              title: pr.title,
              body: pr.body,
              files: files.map(f => f.filename),
              additions: pr.additions,
              deletions: pr.deletions,
              url: pr.html_url
            };

      - name: Send Copilot Solution Notification
        if: github.event_name == 'pull_request' && github.event.action == 'opened'
        uses: dawidd6/action-send-mail@v6
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "🤖 Copilot Solution Ready: ${{ github.event.pull_request.title }}"
          html_body: |
            <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
              <h2 style="color: #0366d6;">🤖 GitHub Copilot Solution Delivered!</h2>
              <p>GitHub Copilot has completed a programming challenge and created a pull request with the solution.</p>
              
              <div style="background-color: #d4edda; padding: 15px; border-radius: 6px; margin: 20px 0; border-left: 4px solid #28a745;">
                <h3>📝 Solution Details</h3>
                <p><strong>Problem:</strong> ${{ github.event.pull_request.title }}</p>
                <p><strong>PR Number:</strong> #${{ github.event.pull_request.number }}</p>
                <p><strong>Author:</strong> ${{ github.event.pull_request.user.login }}</p>
                <p><strong>Status:</strong> Ready for Review</p>
              </div>
              
              <div style="background-color: #f6f8fa; padding: 15px; border-radius: 6px; margin: 20px 0;">
                <h3>📊 Code Changes</h3>
                <p><strong>Lines Added:</strong> +${{ github.event.pull_request.additions }}</p>
                <p><strong>Lines Deleted:</strong> -${{ github.event.pull_request.deletions }}</p>
                <p><strong>Files Modified:</strong> ${{ github.event.pull_request.changed_files }}</p>
              </div>
              
              <div style="background-color: #e1f5fe; padding: 15px; border-radius: 6px; margin: 20px 0;">
                <h3>🔍 Review Required</h3>
                <p>The solution is ready for your review. Please:</p>
                <ul>
                  <li>Review the code implementation</li>
                  <li>Test the solution with provided examples</li>
                  <li>Check for proper error handling</li>
                  <li>Verify comments and documentation</li>
                  <li>Approve or request changes</li>
                </ul>
              </div>
              
              <div style="text-align: center; margin: 30px 0;">
                <a href="${{ github.event.pull_request.html_url }}" 
                   style="background-color: #0366d6; color: white; padding: 12px 24px; text-decoration: none; border-radius: 6px; display: inline-block;">
                  📖 Review Pull Request
                </a>
              </div>
              
              <div style="background-color: #fff3cd; padding: 15px; border-radius: 6px; margin: 20px 0;">
                <h3>💡 Pro Tip</h3>
                <p>You can request modifications by commenting on the PR, and Copilot will respond with updates!</p>
              </div>
              
              <p style="margin-top: 30px; color: #586069; font-size: 12px;">
                Repository: ${{ github.repository }}<br>
                PR URL: ${{ github.event.pull_request.html_url }}<br>
                Created: ${{ github.event.pull_request.created_at }}<br>
                This is an automated notification from GitHub Actions.
              </p>
            </div>
          to: sean.esparagoza@gmail.com
          from: GitHub Copilot Monitor

      - name: Send Solution Merged Notification
        if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
        uses: dawidd6/action-send-mail@v6
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "✅ Programming Solution Merged: ${{ github.event.pull_request.title }}"
          html_body: |
            <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
              <h2 style="color: #28a745;">✅ Solution Successfully Merged!</h2>
              <p>The programming challenge solution has been reviewed and merged into the main branch.</p>
              
              <div style="background-color: #d4edda; padding: 15px; border-radius: 6px; margin: 20px 0; border-left: 4px solid #28a745;">
                <h3>🎉 Completion Summary</h3>
                <p><strong>Problem:</strong> ${{ github.event.pull_request.title }}</p>
                <p><strong>Solution Author:</strong> GitHub Copilot</p>
                <p><strong>Reviewed by:</strong> ${{ github.event.pull_request.merged_by.login }}</p>
                <p><strong>Merged at:</strong> ${{ github.event.pull_request.merged_at }}</p>
              </div>
              
              <div style="background-color: #e1f5fe; padding: 15px; border-radius: 6px; margin: 20px 0;">
                <h3>📈 Challenge Complete</h3>
                <p>This programming challenge has been successfully completed. The solution is now available in the repository and can be used as:</p>
                <ul>
                  <li>Reference implementation</li>
                  <li>Learning material</li>
                  <li>Base for future challenges</li>
                  <li>Code review examples</li>
                </ul>
              </div>
              
              <p style="margin-top: 30px; color: #586069; font-size: 12px;">
                Repository: ${{ github.repository }}<br>
                This challenge is now complete and archived.<br>
                Ready for the next programming challenge!
              </p>
            </div>
          to: sean.esparagoza@gmail.com
          from: GitHub Programming Challenge System
