name: Email Automation

on:
  schedule:
    - cron: "0 9 * * *" # Runs daily at 9 AM UTC
  workflow_dispatch: # Allows manual trigger
  push: # Trigger on push events
    branches: [main]

jobs:
  send-email:
    runs-on: ubuntu-latest
    steps:
      - name: Send mail
        if: always()
        uses: dawidd6/action-send-mail@v6
        with:
          # Mail server settings
          server_address: smtp.gmail.com
          server_port: 465
          # User credentials
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          # Email content
          subject: ${{ github.job }} job of ${{ github.repository }} has ${{ job.status }}
          body: |
            Hello!

            The ${{ github.job }} job in workflow ${{ github.workflow }} 
            of ${{ github.repository }} has ${{ job.status }}.

            Commit: ${{ github.sha }}
            Author: ${{ github.actor }}
            Timestamp: ${{ github.event.head_commit.timestamp }}

            This is an automated email from your GitHub Actions workflow.

            Best regards,
            GitHub Actions Bot
          # Recipients - UPDATE THESE EMAIL ADDRESSES
          to: sean.esparagoza@gmail.com
          from: GitHub Actions Automation
